version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=auction_db
      - AUCTION_INTERVAL=2m
      - AUCTION_CHECK_INTERVAL=10s
      - AUCTION_CONTEXT_TIMEOUT=30s
      - GIN_MODE=debug
    command: sh -c "/auction"
    networks:
      - localNetwork
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork

  # Servi√ßo para executar testes
  test:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=test_auction_db
      - AUCTION_INTERVAL=30s
      - AUCTION_CHECK_INTERVAL=5s
      - AUCTION_CONTEXT_TIMEOUT=10s
      - GIN_MODE=test
    command: sh -c "go test ./... -v -cover"
    networks:
      - localNetwork
    depends_on:
      - mongodb
    profiles:
      - test

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge